- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/content/new-sponsored-list.marko
- packages/common/components/blocks/new-standard-footer.marko
Before height adjustment:
After height adjustment:
Footer:
Sponsored:
> Styling changes to footer, sponsored & mid blocks

- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/blocks/content/new-list.marko
- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/blocks/new-standard-header.marko
Center image with long titles:
> Make styling changes to headline news

- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/new-standard-head-styles.marko
> Fix mobile alignment of content in mid-block

- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/new-standard-head-styles.marko
Decreased font size:
Mobile view (still centered):
> Decrease font-size & keep footer centered on mobile

- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/blocks/content/new-list.marko
- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/content/new-sponsored-list.marko
- packages/common/components/blocks/new-standard-advertisement.marko
- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/blocks/new-standard-header.marko
- packages/common/components/new-standard-head-styles.marko
- tenants/sdce/config/core.js
> Increase template width to keep styling around ad slots

- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/new-standard-advertisement.marko
- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/layouts/new-standard.marko
- packages/common/components/new-standard-head-styles.marko
Before:
After:
Removed white space under ad:
> Adjust styling to account for email on acid testing

- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/new-standard-head-styles.marko
Before head styling class added:
After head styling class added:
Image height not filling table/gap:
After changes:
> Make styling adjustments mid and footer blocks

- packages/common/components/blocks/content/new-featured.marko
- packages/common/graphql/fragments/content-list.js
It will now split contacts & all other content into arrays to use for watermark & title and standard content display.
> Convert Feature block to support contacts

- packages/common/components/layouts/new-standard.marko
Currently only allowing 3 articles to show, now there is no limit
> Remove limit in “lower” section

- tenants/fcp/config/core.js
> Fix missing footer logo image for fleet-maintenance-report template

- packages/common/components/blocks/content/new-sponsored-list.marko
- packages/common/components/blocks/new-standard-advertisement.marko
- packages/common/components/dpm/emailx.marko
- packages/common/components/new-standard-head-styles.marko
Native-X ads will now stack & Email-X ads will "fit" within the black newsletter border
> Adjust how ads are displaying on mobile view

- tenants/fcp/templates/headline-news.marko
> Add space between banner ad and newsletter title (FCP-Headline News)

- tenants/fcp/config/email-x.js
> Remove 2nd Email-X banner ad from ‘Fleet Maintenance Report’ nl

- packages/common/components/blocks/content/new-sponsored-list.marko
This will now "hide" the extra 'Sponsored' tag on Outlook Office 365, Outlook 2010, 2013, 2016, & 2019
> Add Outlook styling for sponsored content

- tenants/fcp/config/email-x.js
@Shinsina Missed this one... Thought she put in a duplicate entry
> Remove 2nd ad slot ‘Construction Zone Safety’

- tenants/ooh/config/core.js
> Add header logo for OEM Show Report

- tenants/fcp/config/email-x.js
Breaking Ground: (shows same ad)
Headline News: (shows same ad)
> Edit Email X ads for Rental Watch & both IronPros

- tenants/fcp/config/email-x.js
- tenants/fcp/templates/breaking-ground-ironpros.marko
- tenants/fcp/templates/headline-news-ironpros.marko
Breaking Ground IronPros: 2 ad slots & 2 Sponsored ad placements:
Headline News IronPros: 1 ad slot and 1 Sponsored ad placement
> IronPros template ad/sponsored changes

- tenants/gip/config/email-x.js
> Remove secondary 600x100 EmailX ad GIP Tech Report

- packages/common/components/blocks/content/ironpros-sponsored-secondary.marko
- packages/common/components/blocks/content/ironpros-sponsored.marko
- packages/common/components/blocks/content/ironpros-workwear.marko
- packages/common/components/blocks/ironpros-header.marko
> IronPros: rearrange header logos, add spacing under 2nd ad, standardize 'Sponsored' section font

- packages/common/components/blocks/content/new-mid.marko
> Update imgOptions for mid block

- tenants/scn/templates/global-supply-chain-insights.marko
> Use ‘Mid’ & ‘Lower’ for Global Supply Chain newsletter sections

- packages/common/components/new-standard-head-styles.marko
Unable to 'test'. Email on Acid doesn't show what is in the Trello card, but this would prevent the table from decreasing to 95% (staying at 100% width)
> Add wrap10 to @media:479px to prevent table size decrease

- packages/common/components/blocks/content/simple-list-item.marko
> Add target=“_blank” for content links

- packages/common/components/blocks/header.marko
- tenants/fcp/config/core.js
> Update header & adjust styling for Elevating Safety newsletter
