parameter1/ac-business-media-newsletters

- packages/common/components/blocks/content/sponsored-list.marko
- packages/common/components/blocks/footer/dss.marko
- packages/common/components/blocks/footer/gip.marko
- packages/common/components/blocks/footer/sso.marko
Ref parameter1/ac-business-media-websites#267, change imgix urls
> Update images to use master imgix source

- packages/common/components/layouts/standard.marko
- tenants/fcp/config/core.js
> Allows for config value to be set on each NL.

- packages/common/components/blocks/marko.json
- packages/common/components/blocks/new-standard-header.marko
- tenants/sdce/marko.json
> Create static version of new standard header layout

- packages/common/components/layouts/marko.json
- packages/common/components/layouts/new-standard.marko
> Create static new standard layout

- packages/common/components/blocks/new-standard-header.marko
> Create dynamic new-standard-header

- packages/common/components/blocks/new-standard-footer.marko
> Update footer for readability

- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/new-standard-header.marko
> Update alignments on header and block sections

- packages/common/components/blocks/content/new-featured.marko
- tenants/sdce/config/core.js
> Update featured image styling

- tenants/sdce/config/core.js
> Change primary color sdce newsletters

- packages/common/components/blocks/content/marko.json
- packages/common/components/blocks/content/new-sponsored-list.marko
- packages/common/components/blocks/new-standard-advertisement.marko
- packages/common/components/layouts/new-standard.marko
- tenants/sdce/config/email-x.js
> Add 2nd sponsored block and adjust emailx 

- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/blocks/content/new-list.marko
- packages/common/components/blocks/content/new-mid.marko
- packages/common/components/blocks/content/new-sponsored-list.marko
- packages/common/components/new-standard-head-styles.marko
Desktop:
Media 590px:
Media 450px:
> Adjust layout to support mobile views

- packages/common/components/blocks/content/marko.json
- packages/common/components/blocks/content/new-sponsored-list.marko
- packages/common/components/blocks/new-standard-header.marko
- packages/common/components/layouts/new-standard.marko
- tenants/gip/config/brands.js
- tenants/gip/config/core.js
- tenants/gip/config/email-x.js
- tenants/gip/templates/snowpro.marko
> Create snowPro newsletter

- .travis.yml
Reverts parameter1/ac-business-media-newsletters#55
> Revert "update code for food"

- tenants/ooh/config/core.js
> Change title for editor OOH newsletters

- tenants/gip/config/core.js
> Update editor image

- tenants/ooh/config/brands.js
> Add “-“ for OEM brand name

- tenants/fcp/templates/show-report.marko
- tenants/fl/templates/show-report.marko
- tenants/ooh/templates/show-report.marko
- tenants/sdce/templates/show-report.marko
> Create ‘Show Report’ newsletter for FCP, OOH, FL & SDCE

- packages/common/components/blocks/content/marko.json
- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/layouts/new-standard.marko
- tenants/fcp/config/core.js
- tenants/fcp/templates/show-report.marko
- tenants/fl/templates/show-report.marko
- tenants/gip/templates/show-report.marko
- tenants/ooh/templates/show-report.marko
- tenants/sdce/templates/show-report.marko
> Change brand to fcp for Show Report template

- tenants/fcp/config/email-x.js
> Remove 2nd banner from Lube Report-FCP

- package.json
- packages/common/package.json
- tenants/fcp/package.json
- tenants/gip/package.json
- tenants/ooh/package.json
- tenants/scn/package.json
- yarn.lock
This will fix the issue with sites being removed from newsletters.
> `parameter1/base-cms @ v2.78.1` dep upgrades

- tenants/scn/config/core.js
> Drop (SDCE) from newsletter name for Show Report.

- tenants/gip/config/core.js
> Update gip editor image Snow Pro newsletter

- tenants/fcp/config/core.js
> Update editor image ‘Construction Technology’ FCP

- tenants/fcp/templates/headline-news.marko
> Move banner ad to top of NL for a test FCP-Headline News

- tenants/fcp/config/core.js
> Change editor for Breaking Ground nl (FCP)

- tenants/fcp/config/core.js
- tenants/fcp/config/email-x.js
- tenants/fcp/templates/construction-and-workforce-management.marko
> Create new template; 'Construction & Workforce Management'

- tenants/fcp/config/email-x.js
> Remove ad slot from power rental

- tenants/fcp/config/core.js
> Update primary color for ‘Elevating Safety’ FCP

- packages/common/components/blocks/content/new-featured.marko
> Omit brand if brand is in editor title.

- tenants/gip/templates/show-report.marko
> Add 3rd ‘Sponsored’ block for Show Report-GIP

- tenants/scn/config/core.js
> Adjust editor for SCN-Headline News

- tenants/gip/templates/show-report.marko
> Adjust skip to content list to allow for more content

- tenants/gip/config/core.js
> Update brandName for SnowPro

- tenants/fcp/config/email-x.js
> Remove banner-2 ad slot on Rental Market Watch

- packages/common/components/blocks/content/ironpros-equipment.marko
- packages/common/components/blocks/content/ironpros-featured.marko
- packages/common/components/blocks/content/ironpros-sponsored.marko
- packages/common/components/blocks/content/ironpros-technology.marko
- packages/common/components/blocks/content/ironpros-workwear.marko
- packages/common/components/blocks/ironpros-footer.marko
- tenants/fcp/config/core.js
> IronPros newsletter styling adjustments

- tenants/gip/config/email-x.js
> Remove 2nd banner add-Lawn Care (GIP)

- tenants/gip/config/core.js
> Update SnowPro editor

- tenants/fcp/config/core.js
- tenants/fcp/config/email-x.js
- tenants/fcp/templates/show-report.marko
> Adjust FCP-Show Report template

- packages/common/components/blocks/content/new-featured.marko
- packages/common/components/blocks/content/new-mid.marko
> Adjust top & mid block for dark mode

- packages/common/components/blocks/content/ironpros-featured.marko
> Remove editor & newsletter info for IronPros

- packages/common/components/blocks/advertisement.marko
- packages/common/components/blocks/content/marko.json
- packages/common/components/blocks/content/simple-list-item.marko
- packages/common/components/blocks/content/simple-list.marko
- packages/common/components/blocks/content/simple-sponsored.marko
- packages/common/components/blocks/ironpros-header.marko
- packages/common/components/blocks/standard-footer.marko
- packages/common/components/blocks/standard-header.marko
- tenants/fcp/templates/breaking-ground-ironpros.marko
- tenants/fcp/templates/headline-news-ironpros.marko
- tenants/scn/config/core.js
- tenants/scn/templates/global-supply-chain-insights.marko
> Create 'simple' styling layout for IronPros & global supply chain insights NLs

- packages/common/components/blocks/content/ironpros-sponsored-secondary.marko
- packages/common/components/blocks/content/ironpros-sponsored.marko
- packages/common/components/blocks/content/simple-list-item.marko
- packages/common/components/blocks/ironpros-advertisement.marko
- packages/common/components/blocks/ironpros-footer.marko
- packages/common/components/blocks/ironpros-header.marko
- packages/common/components/blocks/standard-header.marko
- packages/common/components/new-standard-head-styles.marko
- tenants/fcp/config/core.js
- tenants/fcp/templates/breaking-ground-ironpros.marko
- tenants/fcp/templates/headline-news-ironpros.marko
- tenants/scn/config/core.js
- tenants/scn/templates/global-supply-chain-insights.marko
> New template adjustments

- packages/common/components/blocks/ironpros-header.marko
- packages/common/components/new-standard-head-styles.marko
> Ironpros table blowout fix

- tenants/fcp/config/core.js
> Set Brandon Noel, editor of Infrastructure Impact

- tenants/gip/config/core.js
> Update right header image snowPro psc

- packages/common/components/layouts/psc.marko
Currently they are adding a footer in Omeda
> Remove footer from psc layout

- tenants/gip/templates/show-report.marko
> Rearrange layout for GIP Show Report

- packages/common/components/blocks/header/view-online.marko
- packages/common/components/blocks/ironpros-footer.marko
- packages/common/components/blocks/ironpros-header.marko
- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/blocks/new-standard-header.marko
- packages/common/components/blocks/psc-footer.marko
- packages/common/components/blocks/simple-footer.marko
- packages/common/components/blocks/simple-header.marko
- packages/common/components/blocks/simple-show-header.marko
- packages/common/components/blocks/standard-footer.marko
- packages/common/components/blocks/standard-header.marko
- packages/common/components/elements/psc-banner.marko
- packages/common/components/new-standard-head-styles.marko
> Replace all ‘ACBM’ references with ‘IRONMARKETS’

- packages/common/components/blocks/ironpros-footer.marko
- packages/common/components/blocks/new-standard-footer.marko
- packages/common/components/blocks/psc-footer.marko
- packages/common/components/blocks/simple-footer.marko
- packages/common/components/blocks/standard-footer.marko
> Replace acbmail.com with ironmarketmail.com

- packages/common/components/blocks/header.marko
- packages/common/components/blocks/marko.json
- tenants/fcp/config/core.js
- tenants/fcp/templates/elevating-safety.marko
> Update Elevating safety header block

- tenants/fcp/templates/breaking-ground-ironpros.marko
> Rearrange Breaking Ground Ironpros layout to match Breaking Ground layout (ads)

- packages/common/components/blocks/simple-footer.marko
Food Logistics brandName:
SDCE brandName:
> Add footer option for SDCE newsletters

- tenants/fcp/templates/construction-technology.marko
- tenants/fcp/templates/elevating-safety.marko
- tenants/fcp/templates/truck-report.marko
> Remove bottom leaderboard

- packages/common/components/blocks/ironpros-footer.marko
- tenants/fcp/config/brands.js
- tenants/fcp/config/core.js
> Update 2 IRONPROS templates and config

- tenants/fcp/config/core.js
> Update Asphalt and Concrete Showcase newsletter headers

- tenants/fcp/config/core.js
> Update ‘equipment-today-psc’ header

- tenants/ooh/templates/show-report.marko
> Move banner-1 to top of template

- tenants/fcp/config/core.js
> Update rental psc header

- packages/common/components/blocks/header/marko.json
- packages/common/components/blocks/header/psc-image.marko
- packages/common/components/blocks/psc-header.marko
- tenants/ooh/config/core.js
> Update OEM Product Showcase header

- packages/common/components/blocks/header/marko.json
- packages/common/components/blocks/header/psc-image.marko
- packages/common/components/blocks/psc-header.marko
- tenants/ooh/config/core.js
Reverts parameter1/ac-business-media-newsletters#203
> Revert "Update OEM Product Showcase header"

- tenants/ooh/config/core.js
> Upload new header image OEM product showcase
